name: first work flow

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
    name: deploy to dev
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
outputs: ${{  }}




